FROM "node:14.9.0"
#// or FROM "node:14.9.0-alpine"

RUN npm i -g  "create-react-app"
RUN create-react-app  "app-react"
WORKDIR /app-react
RUN npm install
RUN npm install axios
ADD  "public"  "public"
ADD  "src"  "src"
EXPOSE  80
CMD NODE_ENV=production PORT=80 npm run start
